### PR TITLE
Adds mailer to mail participants discord invite

### PR DESCRIPTION
**Pull request by narbs91**
### What does it do?

- Adding this mailing method as a fallback method to passing out the discord invites to registrants of the web3con hackathon
- onboarded nodemailer to handle mailing
- added mailMeta type to house domain representation of a mail object
- changed sample.csv to hacker.csv and added email as a field in the row

### Any helpful background information?

We need a way to pass along the discord invite to the hackthon to registrants for them to be able to join.  The hope by inviting them personally, this will reduce bad actors/bots from entering the discord with a combination of disabling invites from any role but the `mod` role. 

### Any new dependencies? Why were they added?

nodemailer for being able to mail

### CODE REVIEW

**Comment by jcstein** [comment]
This looks good to me, thank you @narbs91 for getting this done. Looking forward to testing it out!

**Comment by Dhaiwat10** [comment]
Hey @narbs91 thanks for getting us started here. Is this deployed anywhere?

**Comment by narbs91** [comment]
> Hey @narbs91 thanks for getting us started here. Is this deployed anywhere?

For sure! No this isn't deployed anywhere at the moment.  We certainly could deploy and run it like a lamda but since the CSV is going to be changing constantly we'd need a PR for that every time.  Might be easier for us to run it locally but we can discuss

**Comment by Dhaiwat10** [comment]
Running it locally makes sense. Let's merge

**Comment by narbs91** [comment]
> Running it locally makes sense. Let's merge 

Cool beans!  We need the official email to send the invites from.  Do we want to use the web3con one we have? If so we'll need the credentials to be able to use it.  The alternative is to use a newly created gmail account and share it among ourselves to be able to run the script. 

Thoughts?

**Comment by Dhaiwat10** [comment]
@narbs91 I think we definitely need to send the emails from the original web3con account (with the web3con.dev domain). I'm sure we can get the credentials, yea?

**Comment by narbs91** [comment]
> @narbs91 I think we definitely need to send the emails from the original web3con account (with the web3con.dev domain). I'm sure we can get the credentials, yea?

I'm pretty sure we can, I'll bring it up in the sync tomorrow and let you know.  But yes, they def should be sent from the official email account.  Im wondering if we can test drive this with the sponsors as the "first wave" to get the invites?

**Comment by Dhaiwat10** [comment]
@narbs91 that sounds like a good way to test the setup

**Pull request merged**
